site_name: irgsctool
site_url: https://irgsctool.github.io/dms-irgsc/
repo_url: https://github.com/sshah1502/irgsc/
site_author: Sarang Shah
use_directory_urls: false
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - toc:
      permalink: link
      toc_depth: 4

theme: 
  name: mkdocs
  logo: img/TMTLOGO.PNG
  nav_style: dark
  features:
    - content.action.edit
    - navigation.footer
  icon:
    edit: material/pencil 
    view: material/eye

plugins:
  - git-committers:
      repository: sshah1502/irgsc/
      branch: main
  - optimize
  - offline
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_source: true
            show_category_heading: false
            show_heading: false
            docstring_section_style: spacy
            show_bases: false
            merge_init_into_class: true
            fontcolor: black
  - glightbox
  - search
  - with-pdf:
      cover_title: irgsctool
      cover_subtitle: Software documentation for irgsctool python package
      author: Sarang Shah
      copyright: 

nav:
  - Home: index.md
  - About: about.md
  #- API: apireference.md
  - Tutorials: tutorials.md
  - Acknowledgements: acknowledgements.md
  - License: license.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
